# Generated by Django 2.2.4 on 2019-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exiled_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
