# Generated by Django 2.2.4 on 2019-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exiled_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='score',
            name='game_round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
